# Generated by Django 4.1.7 on 2023-03-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='allergens',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ingredients',
            field=models.CharField(max_length=300),
        ),
    ]
