# Generated by Django 4.1.7 on 2023-03-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0002_alter_listing_allergens_alter_listing_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.URLField(max_length=300),
        ),
    ]
