# Generated by Django 4.1.7 on 2023-03-07 22:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0003_alter_listing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='allergens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=None),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=None),
        ),
    ]
