# Generated by Django 4.1.7 on 2023-03-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0004_alter_listing_allergens_alter_listing_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pickup_by_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
