# Generated by Django 4.1.7 on 2023-03-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0007_listing_restaurant_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='restaurant',
            field=models.CharField(max_length=30),
        ),
    ]
